# Generated by Django 4.2.23 on 2025-11-14 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(help_text='Brief summary for blog listing', max_length=300)),
                ('featured_image', models.ImageField(help_text='Optimal size: 1200x630px for social sharing', upload_to='blog/%Y/%m/%d/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('position', models.IntegerField(choices=[(1, 'Featured - Top Position'), (2, 'Standard - High Priority'), (3, 'Regular - Normal Priority'), (4, 'Archive - Lower Priority')], default=3)),
                ('meta_title', models.CharField(blank=True, help_text='Optional custom title for SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Optional custom description for SEO', max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['position', '-published_date'],
            },
        ),
    ]
