# Generated by Django 4.2.23 on 2025-11-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('dating-advice', 'Dating Advice'), ('online-safety', 'Online Dating Safety'), ('elite-dating', 'Elite Dating Insights'), ('success-stories', 'Success Stories')], default='dating-advice', help_text='Select blog post category', max_length=50),
        ),
    ]
