# Generated by Django 4.2.23 on 2025-11-25 17:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('relationship_status', models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('widowed', 'Widowed')], max_length=20)),
                ('body_type', models.CharField(choices=[('slim', 'Slim'), ('athletic', 'Athletic'), ('average', 'Average'), ('curvy', 'Curvy'), ('full_figured', 'Full Figured')], max_length=20)),
                ('has_children', models.BooleanField(default=False)),
                ('children_details', models.TextField(blank=True)),
                ('is_smoker', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('personality_traits', models.JSONField(default=list)),
                ('communication_style', models.CharField(max_length=100)),
                ('life_priorities', models.JSONField(default=list)),
                ('core_values', models.JSONField(default=list)),
                ('arrangement_preferences', models.JSONField(default=dict)),
                ('lifestyle_interests', models.JSONField(default=list)),
                ('preferred_age_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('preferred_age_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('preferred_distance', models.IntegerField()),
                ('trust_level', models.CharField(choices=[('unverified', 'Unverified'), ('basic', 'Basic Trust'), ('enhanced', 'Enhanced Trust'), ('premium', 'Premium Trust')], default='unverified', max_length=20)),
                ('privacy_settings', models.JSONField(default=dict)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Indicator',
                'verbose_name_plural': 'Trust Indicators',
                'permissions': [('can_view_trust_indicators', 'Can view trust indicators')],
            },
        ),
        migrations.CreateModel(
            name='LegalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(max_length=50)),
                ('privacy_version', models.CharField(max_length=50)),
                ('safety_acknowledged', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Consent',
                'verbose_name_plural': 'Legal Consents',
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'liked_user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'favorite_user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'blocked_user_id')},
            },
        ),
    ]
