# Generated by Django 4.2.23 on 2025-11-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_userprofile_trustindicator_legalconsent_userlike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity', models.CharField(choices=[('Coffee', 'Coffee'), ('Drinks / Wine Bar', 'Drinks / Wine Bar'), ('Dinner', 'Dinner'), ('Walk / Park', 'Walk / Park'), ('Gallery / Museum', 'Gallery / Museum'), ('Movie', 'Movie'), ('Live Music / Comedy', 'Live Music / Comedy'), ('Surprise Me', 'Surprise Me')], max_length=100)),
                ('vibe', models.CharField(choices=[('Chill', 'Chill'), ('Classy', 'Classy'), ('Adventurous', 'Adventurous'), ('Playful', 'Playful'), ('Quiet', 'Quiet')], max_length=100)),
                ('budget', models.CharField(choices=[('Free', 'Free'), ('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('Each pays their way', 'Each pays their way')], max_length=50)),
                ('duration', models.CharField(choices=[('45 min', '45 min'), ('60 min', '60 min'), ('90 min', '90 min'), ('2 hours', '2 hours'), ('3 hours', '3 hours')], max_length=50)),
                ('date_time', models.DateTimeField()),
                ('area', models.CharField(max_length=100)),
                ('group_size', models.CharField(choices=[('1_on_1', '1 on 1'), ('small_group', 'Small group (3–4)'), ('group', 'Group (5+)')], max_length=50)),
                ('audience', models.CharField(choices=[('anyone', 'Anyone'), ('women_only', 'Women only'), ('men_only', 'Men only')], max_length=50)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Event',
                'verbose_name_plural': 'Date Events',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='DateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('date_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dateevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date View',
                'verbose_name_plural': 'Date Views',
                'unique_together': {('user', 'date_event')},
            },
        ),
    ]
