# Generated by Django 4.2.23 on 2025-11-27 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_dateevent_dateview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=20, null=True)),
                ('body_type', models.CharField(blank=True, max_length=20, null=True)),
                ('has_children', models.BooleanField(default=False, null=True)),
                ('children_details', models.TextField(blank=True, null=True)),
                ('is_smoker', models.BooleanField(default=False, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('personality_traits', models.JSONField(blank=True, default=list, null=True)),
                ('communication_style', models.CharField(blank=True, max_length=100, null=True)),
                ('life_priorities', models.JSONField(blank=True, default=list, null=True)),
                ('core_values', models.JSONField(blank=True, default=list, null=True)),
                ('arrangement_preferences', models.JSONField(blank=True, default=dict, null=True)),
                ('lifestyle_interests', models.JSONField(blank=True, default=list, null=True)),
                ('preferred_age_min', models.IntegerField(blank=True, null=True)),
                ('preferred_age_max', models.IntegerField(blank=True, null=True)),
                ('preferred_distance', models.IntegerField(blank=True, null=True)),
                ('trust_level', models.CharField(blank=True, max_length=20, null=True)),
                ('privacy_settings', models.JSONField(blank=True, default=dict, null=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='pending_profile_photos/')),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
