# Generated by Django 4.2.23 on 2025-11-27 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_profileeditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileeditrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profileeditrequest',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profileeditrequest',
            name='looking_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_type',
            field=models.CharField(choices=[('slim', 'Slim'), ('athletic', 'Athletic'), ('average', 'Average'), ('curvy', 'Curvy'), ('full_figured', 'Full Figured')], default='average', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='communication_style',
            field=models.CharField(default='Friendly', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_age_max',
            field=models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_age_min',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_distance',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('widowed', 'Widowed')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='story',
            field=models.TextField(default='No story provided yet.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
