# Generated by Django 4.2.23 on 2025-11-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profileeditrequest_gender_profileeditrequest_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Original CSV profile image URL', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_type', models.CharField(choices=[('additional', 'Additional Image'), ('private', 'Private Image')], max_length=20)),
                ('position', models.IntegerField(default=0, help_text='Position for ordering: 1-4 for additional, 1-5 for private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.userprofile')),
            ],
            options={
                'verbose_name': 'User Profile Image',
                'verbose_name_plural': 'User Profile Images',
                'ordering': ['image_type', 'position'],
                'unique_together': {('user_profile', 'image_type', 'position')},
            },
        ),
    ]
