# Generated by Django 4.2.23 on 2025-12-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('message_deleted', 'Message Deleted'), ('profile_view', 'Profile Viewed'), ('like_given', 'Like Given'), ('like_received', 'Like Received'), ('favorite', 'Favorite Toggled'), ('block', 'Block Toggled'), ('date_created', 'Date Created'), ('date_joined', 'Date Joined'), ('date_cancelled', 'Date Cancelled'), ('profile_edit', 'Profile Edited'), ('profile_edit_request', 'Profile Edit Requested'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='website_use_user_id_d1b1be_idx'), models.Index(fields=['activity_type', 'created_at'], name='website_use_activit_6cbde5_idx'), models.Index(fields=['ip_address', 'created_at'], name='website_use_ip_addr_9b82af_idx')],
            },
        ),
    ]
