# Generated by Django 4.2.23 on 2025-12-01 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_message_deleted_at_message_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('message_deleted', 'Message Deleted'), ('profile_view', 'Profile Viewed'), ('like_given', 'Like Given'), ('like_received', 'Like Received'), ('favorite', 'Favorite Toggled'), ('block', 'Block Toggled'), ('date_created', 'Date Created'), ('date_joined', 'Date Joined'), ('date_cancelled', 'Date Cancelled'), ('profile_edit', 'Profile Edited'), ('profile_edit_request', 'Profile Edit Requested'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected'), ('private_access_requested', 'Private Access Requested'), ('private_access_granted', 'Private Access Granted'), ('private_access_revoked', 'Private Access Revoked'), ('private_access_denied', 'Private Access Denied')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrivateAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message explaining why access is requested')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for denying or revoking access')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_access_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_access_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Access Request',
                'verbose_name_plural': 'Private Access Requests',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'target_user')},
            },
        ),
    ]
