# Generated by Django 4.2.23 on 2025-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_useractivitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_profile_id', models.IntegerField(help_text='ID from external profile system', unique=True)),
                ('external_user_id', models.IntegerField(help_text='user_id from external profile system')),
                ('django_user_id', models.IntegerField(help_text='Actual Django user.id')),
                ('username', models.CharField(help_text='Username for verification', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User ID Mapping',
                'verbose_name_plural': 'User ID Mappings',
                'db_table': 'user_id_mapping',
                'indexes': [models.Index(fields=['external_profile_id'], name='user_id_map_externa_e941f7_idx'), models.Index(fields=['username'], name='user_id_map_usernam_0a44fc_idx'), models.Index(fields=['django_user_id'], name='user_id_map_django__bf4c0f_idx')],
            },
        ),
    ]
