# Generated by Django 4.2.23 on 2025-12-03 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_useridmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateevent',
            name='group_size',
            field=models.CharField(choices=[('1_on_1', '1 on 1'), ('small_group', 'Small group (3-4)'), ('group', 'Group (5+)')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrivateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='private_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.IntegerField(default=1, help_text='Position for ordering (1-5)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Image',
                'verbose_name_plural': 'Private Images',
                'ordering': ['position', 'uploaded_at'],
            },
        ),
    ]
