# Generated by Django 4.2.23 on 2025-10-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_blog_options_blog_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-position', '-published_at', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blog',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Manual ordering position (higher numbers appear first)'),
        ),
    ]
