# Generated by Django 4.2.23 on 2025-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_blog_options_blog_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for hero image accessibility & SEO', max_length=125),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Custom meta description for SEO (optional)', max_length=320),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom meta title (optional, defaults to blog title)', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='social_sharing_image',
            field=models.ImageField(blank=True, help_text='Custom image for social media sharing (1200x630px recommended)', null=True, upload_to='blog/social/'),
        ),
    ]
