# Generated by Django 4.2.23 on 2025-10-31 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0024_alter_blog_options_remove_blog_image_alt_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verification_sent_at',
            new_name='email_verification_sent_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='verification_token',
            new_name='email_verification_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
