# Generated by Django 4.2.23 on 2025-11-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_rename_verification_sent_at_profile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='inactivity_last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='inactivity_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='marked_for_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_approval_last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_approval_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completion_last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completion_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmailReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('profile_completion', 'Profile Completion'), ('profile_approval', 'Profile Approval'), ('inactivity', 'Inactivity')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='pages.profile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
