# Generated by Django 4.2.23 on 2025-11-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_profile_email_verification_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='is_private',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='image_type',
            field=models.CharField(choices=[('profile', 'Profile Image'), ('additional', 'Additional Image'), ('private', 'Private Image')], default='profile', max_length=20),
        ),
    ]
