# Generated by Django 4.2.23 on 2025-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_remove_profileimage_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('slim', 'Slim'), ('athletic', 'Athletic'), ('average', 'Average'), ('curvy', 'Curvy'), ('stocky', 'Stocky')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black', 'Black'), ('caucasian', 'Caucasian'), ('hispanic', 'Hispanic'), ('mixed', 'Mixed'), ('middle_eastern', 'Middle Eastern'), ('native', 'Native/Indigenous'), ('pacific_islander', 'Pacific Islander'), ('prefer_not_say', 'Prefer not to say')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='want_children',
            field=models.CharField(blank=True, choices=[('want', 'Want children'), ('dont_want', "Don't want children"), ('not_sure', 'Not sure'), ('open', 'Open to it')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='privateaccessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_profile', 'View Profile'), ('update_profile', 'Update Profile'), ('send_message', 'Send Message'), ('view_blog', 'View Blog'), ('search', 'Search'), ('like', 'Like'), ('block', 'Block'), ('admin_message_sent', 'Admin Message Sent'), ('upload_photo', 'Upload Photo'), ('delete_photo', 'Delete Photo'), ('request_private_access', 'Request Private Access'), ('approve_private_access', 'Approve Private Access'), ('deny_private_access', 'Deny Private Access')], max_length=50),
        ),
    ]
