# Generated by Django 4.2.23 on 2025-11-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_profile_body_type_profile_ethnicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_content_snapshot',
            field=models.JSONField(blank=True, help_text='Stores approved content state', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_approved_at',
            field=models.DateTimeField(blank=True, help_text='When approved state was captured', null=True),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Photo approval status'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='needs_approval',
            field=models.BooleanField(default=False, help_text='New photos need admin approval'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='replaced_image',
            field=models.ForeignKey(blank=True, help_text='Track which photo this replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.profileimage'),
        ),
    ]
